// ◎ ScriptPanel — 腳本串接面板 + Screenplay .md 匯出 + VEO Batch Queue .json 匯出
// P6: 長篇動畫管道的核心輸出模組

import { useEffect, useRef } from 'react';
import { anime } from '../hooks/useAnime';
import { useI18n } from '../i18n/context';
import type { ShotRecord } from '../hooks/usePersistentFlow';
import type { LockEntry } from '../types/vdl';

interface Props {
  shots:      ShotRecord[];
  nodeValues: Record<string, Record<string, string | number>>;
  locks:      Record<string, LockEntry>;
  projectName: string;
}

// ─── 組裝 Screenplay Markdown ────────────────────────────────
function buildScreenplayMarkdown(
  shots: ShotRecord[],
  nodeValues: Record<string, Record<string, string | number>>,
  locks: Record<string, LockEntry>,
  projectName: string,
): string {
  const totalDur = shots.reduce((sum, s) => {
    const dur = Number(nodeValues[`node_04`]?.scene_duration ?? nodeValues[`node_11`]?.seg_duration ?? 10);
    return sum + dur;
  }, 0);

  const lines: string[] = [
    `# VDL-FLOW SCREENPLAY`,
    `## ${projectName}`,
    `### Total Runtime: ${totalDur}s | ${shots.length} shot(s)`,
    `### Generated: ${new Date().toISOString().slice(0, 19).replace('T', ' ')} (UTC)`,
    '',
    '---',
    '',
  ];

  shots.forEach((shot, i) => {
    const n04 = shot.prompts['node_04'] ?? '';
    const n06 = shot.prompts['node_06'] ?? '';
    const n07 = shot.prompts['node_07'] ?? '';
    const n09 = shot.prompts['node_09'] ?? '';
    const n10 = shot.prompts['node_10'] ?? '';
    const n11 = shot.prompts['node_11'] ?? '';

    // Extract readable values from node values if available
    const v04 = nodeValues['node_04'] ?? {};
    const v06 = nodeValues['node_06'] ?? {};
    const v07 = nodeValues['node_07'] ?? {};
    const v11 = nodeValues['node_11'] ?? {};

    const shotId  = String(v07.shot_id ?? v04.scene_id ?? `SH${String(i + 1).padStart(2, '0')}`);
    const dur     = Number(v04.scene_duration ?? v11.seg_duration ?? 10);
    const scene   = String(v04.scene_location ?? '');
    const action  = String(v04.action_desc ?? '');
    const dialogue = String(v04.dialogue ?? '');

    lines.push(`## SHOT ${i + 1} — ${shotId} (${dur}s)`);
    lines.push('');
    if (scene)    lines.push(`**Scene:** ${scene}`);
    if (action)   lines.push(`**Action:** ${action}`);
    if (dialogue) lines.push(`**Dialogue:** ${dialogue}`);
    lines.push('');
    lines.push(`**Camera:** ${String(v07.shot_type ?? '')} ${String(v07.focal_mm ?? '')}mm, ${String(v07.movement ?? '')}`);
    lines.push(`**VDL:** ${v06.kelvin ?? locks.kelvin?.value ?? ''}K, EV${v06.ev ?? locks.ev?.value ?? ''}, contrast ${v06.contrast ?? locks.contrast?.value ?? ''}, sat ${v06.saturation ?? locks.saturation?.value ?? ''}`);
    if (n09) lines.push(`**Style:** ${n09.slice(0, 200)}${n09.length > 200 ? '...' : ''}`);
    if (v11.transition) lines.push(`**Transition:** ${v11.transition}`);
    lines.push('');

    // Analysis deviation (NODE 10)
    if (n10) {
      lines.push('### Reference Analysis');
      lines.push('```');
      lines.push(n10);
      lines.push('```');
      lines.push('');
    }

    // Full prompt assembly (NODE 11 or NODE 10)
    lines.push('### Prompt Assembly');
    lines.push('```');
    if (n10) lines.push(n10);
    if (n11) lines.push(n11);
    lines.push('```');
    lines.push('');

    // QA scores
    if (shot.qaScores.length === 6) {
      const labels = ['ΔKelvin', 'ΔE', 'CLIP', 'ObjRecall', 'DepthCorr', 'NDFDelta'];
      lines.push(`**QA:** ${labels.map((l, j) => `${l}=${shot.qaScores[j]}`).join(' | ')}`);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  });

  lines.push(`> Generated by VDL-FLOW — Visual Narrative Closed-Loop Animation Pipeline`);
  return lines.join('\n');
}

// ─── 組裝 VEO Batch Queue JSON ──────────────────────────────
function buildVEOBatchQueue(
  shots: ShotRecord[],
  nodeValues: Record<string, Record<string, string | number>>,
  locks: Record<string, LockEntry>,
): object[] {
  return shots.map((shot, i) => {
    const v04 = nodeValues['node_04'] ?? {};
    const v06 = nodeValues['node_06'] ?? {};
    const v07 = nodeValues['node_07'] ?? {};
    const v09 = nodeValues['node_09'] ?? {};
    const v11 = nodeValues['node_11'] ?? {};

    const shotId = String(v07.shot_id ?? v04.scene_id ?? `SH${String(i + 1).padStart(2, '0')}`);
    const dur    = Number(v04.scene_duration ?? v11.seg_duration ?? 10);

    // Assemble generation prompt from locked values
    const stylePrefix = String(locks.global_style?.value ?? v09.global_style ?? '');
    const negative    = String(locks.global_negative?.value ?? v09.global_negative ?? '');
    const prompt      = shot.prompts['node_10'] ?? shot.prompts['node_07'] ?? '';

    return {
      shot_index: i + 1,
      shot_id: shotId,
      duration_s: dur,
      prompt,
      style_prefix: stylePrefix,
      negative_prompt: negative,
      transition: String(v11.transition ?? 'dissolve'),
      photometric: {
        kelvin:     Number(locks.kelvin?.value     ?? v06.kelvin     ?? 5500),
        ev:         Number(locks.ev?.value         ?? v06.ev         ?? 0),
        contrast:   Number(locks.contrast?.value   ?? v06.contrast   ?? 0.65),
        saturation: Number(locks.saturation?.value ?? v06.saturation ?? 0.55),
      },
      camera: {
        shot_type:    String(v07.shot_type ?? ''),
        focal_mm:     Number(v07.focal_mm ?? 50),
        movement:     String(locks.movement?.value ?? v07.movement ?? ''),
      },
      qa_scores: shot.qaScores,
    };
  });
}

// ─── 下載工具 ────────────────────────────────────────────────
function downloadFile(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── ScriptPanel 元件 ────────────────────────────────────────

export function ScriptPanel({ shots, nodeValues, locks, projectName }: Props) {
  const { t } = useI18n();
  const containerRef = useRef<HTMLDivElement>(null);
  const timelineRef  = useRef<HTMLDivElement>(null);

  // Anime.js 進場
  useEffect(() => {
    if (!containerRef.current || shots.length === 0) return;
    anime({
      targets: containerRef.current,
      opacity: [0, 1],
      translateY: [20, 0],
      duration: 600,
      easing: 'easeOutCubic',
    });
  }, [shots.length]);

  // Anime.js 時間軸色塊 stagger
  useEffect(() => {
    if (!timelineRef.current || shots.length === 0) return;
    const bars = timelineRef.current.querySelectorAll('[data-tl-bar]');
    if (bars.length === 0) return;
    anime({
      targets: bars,
      scaleX: [0, 1],
      opacity: [0, 1],
      delay: anime.stagger(80),
      duration: 400,
      easing: 'easeOutQuad',
    });
  }, [shots.length]);

  if (shots.length === 0) return null;

  // 計算各鏡���時長
  const shotDurations = shots.map((_, i) => {
    const v04 = nodeValues['node_04'] ?? {};
    const v11 = nodeValues['node_11'] ?? {};
    return Number(v04.scene_duration ?? v11.seg_duration ?? 10);
  });
  const totalDur = shotDurations.reduce((a, b) => a + b, 0);

  const handleExportScreenplay = () => {
    const md = buildScreenplayMarkdown(shots, nodeValues, locks, projectName);
    const ts = new Date().toISOString().slice(0, 10);
    downloadFile(md, `${projectName}-screenplay-${ts}.md`, 'text/markdown');
  };

  const handleExportVEO = () => {
    const queue = buildVEOBatchQueue(shots, nodeValues, locks);
    const ts = new Date().toISOString().slice(0, 10);
    downloadFile(JSON.stringify(queue, null, 2), `${projectName}-veo-batch-${ts}.json`, 'application/json');
  };

  // 色塊配色（循環）
  const BAR_COLORS = ['#3B1D8F', '#2A1A4A', '#1e3a5f', '#4a1a3a', '#1a3a2a'];

  return (
    <div ref={containerRef} style={{ marginTop: 16, padding: '12px 16px', background: '#0F0B1A', border: '1px solid #2A1A4A', borderRadius: 2, opacity: 0 }}>
      {/* 標題 */}
      <div style={{ fontSize: 10, color: '#A78BFA', letterSpacing: 2, marginBottom: 12 }}>
        {t('script.title')}
      </div>

      {/* 時間軸視覺化 */}
      <div style={{ marginBottom: 12 }}>
        <div style={{ fontSize: 8, color: '#818387', marginBottom: 6, letterSpacing: 1 }}>
          {t('script.timeline', { total: String(totalDur), count: String(shots.length) })}
        </div>
        <div ref={timelineRef} style={{ display: 'flex', height: 24, borderRadius: 2, overflow: 'hidden', background: '#111' }}>
          {shotDurations.map((dur, i) => {
            const widthPct = totalDur > 0 ? (dur / totalDur) * 100 : 100 / shots.length;
            return (
              <div
                key={i}
                data-tl-bar
                title={`Shot ${i + 1}: ${dur}s`}
                style={{
                  width: `${widthPct}%`,
                  background: BAR_COLORS[i % BAR_COLORS.length],
                  borderRight: i < shots.length - 1 ? '1px solid #0F0B1A' : 'none',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: 7, color: '#D9D9D6', letterSpacing: 0.5,
                  opacity: 0, transformOrigin: 'left center',
                  overflow: 'hidden', whiteSpace: 'nowrap',
                  cursor: 'default',
                }}
              >
                {widthPct > 8 ? `${i + 1} (${dur}s)` : `${i + 1}`}
              </div>
            );
          })}
        </div>
        {/* 時間刻度 */}
        <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 2 }}>
          <span style={{ fontSize: 7, color: '#333' }}>0s</span>
          <span style={{ fontSize: 7, color: '#333' }}>{totalDur}s</span>
        </div>
      </div>

      {/* 匯出按鈕 */}
      <div style={{ display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap' }}>
        <button
          onClick={handleExportScreenplay}
          style={{
            fontSize: 9, padding: '4px 12px', background: 'transparent',
            border: '1px solid #A78BFA', color: '#D9D9D6', borderRadius: 2,
            cursor: 'pointer', fontFamily: 'inherit', letterSpacing: 0.5,
          }}
        >
          {t('script.exportScreenplay')}
        </button>
        <button
          onClick={handleExportVEO}
          style={{
            fontSize: 9, padding: '4px 12px', background: 'transparent',
            border: '1px solid #4C4E56', color: '#818387', borderRadius: 2,
            cursor: 'pointer', fontFamily: 'inherit', letterSpacing: 0.5,
          }}
        >
          {t('script.exportVEO')}
        </button>
      </div>

      {/* 腳本預覽 (可展開) */}
      <details>
        <summary style={{ fontSize: 9, color: '#6B5A8A', cursor: 'pointer', marginBottom: 8, letterSpacing: 1 }}>
          {t('script.preview')}
        </summary>
        <div style={{ padding: '8px 0' }}>
          {shots.map((shot, i) => {
            const v04 = nodeValues['node_04'] ?? {};
            const v07 = nodeValues['node_07'] ?? {};
            const v06 = nodeValues['node_06'] ?? {};
            const v11 = nodeValues['node_11'] ?? {};
            const shotId = String(v07.shot_id ?? v04.scene_id ?? `SH${String(i + 1).padStart(2, '0')}`);
            const dur    = shotDurations[i];

            return (
              <div key={shot.shotIndex} style={{ marginBottom: 12, paddingBottom: 12, borderBottom: '1px solid #1a1a2e' }}>
                {/* 鏡頭標題 */}
                <div style={{ fontSize: 9, color: '#D9D9D6', letterSpacing: 1, marginBottom: 4 }}>
                  {t('script.shotHeading', { index: String(i + 1), id: shotId, dur: String(dur) })}
                </div>

                <div style={{ fontSize: 8, color: '#555', lineHeight: 1.8 }}>
                  {v04.scene_location && (
                    <div><span style={{ color: '#818387' }}>{t('script.scene')}:</span> {String(v04.scene_location)}</div>
                  )}
                  {v04.action_desc && (
                    <div><span style={{ color: '#818387' }}>{t('script.action')}:</span> {String(v04.action_desc)}</div>
                  )}
                  {v04.dialogue && (
                    <div><span style={{ color: '#818387' }}>{t('script.dialogue')}:</span> {String(v04.dialogue)}</div>
                  )}
                  <div>
                    <span style={{ color: '#818387' }}>{t('script.camera')}:</span>{' '}
                    {String(v07.shot_type ?? '')} {v07.focal_mm ? `${v07.focal_mm}mm` : ''} {String(v07.movement ?? '')}
                  </div>
                  <div>
                    <span style={{ color: '#818387' }}>{t('script.vdl')}:</span>{' '}
                    {v06.kelvin ?? locks.kelvin?.value ?? ''}K, EV{v06.ev ?? locks.ev?.value ?? ''}, contrast {v06.contrast ?? locks.contrast?.value ?? ''}, sat {v06.saturation ?? locks.saturation?.value ?? ''}
                  </div>
                  {v11.transition && (
                    <div><span style={{ color: '#818387' }}>{t('script.transition')}:</span> {String(v11.transition)}</div>
                  )}
                </div>

                {/* QA 分數 */}
                {shot.qaScores.length === 6 && (
                  <div style={{ display: 'flex', gap: 4, marginTop: 4, flexWrap: 'wrap' }}>
                    {['ΔK', 'ΔE', 'CLIP', 'OBJ', 'DEP', 'NDF'].map((label, j) => (
                      <span key={j} style={{ fontSize: 7, color: '#5A4A6A', background: '#111', padding: '0 3px', borderRadius: 1 }}>
                        {label}:{shot.qaScores[j]}
                      </span>
                    ))}
                  </div>
                )}

                {/* 提示詞摘要 */}
                {shot.prompts['node_10'] && (
                  <details style={{ marginTop: 4 }}>
                    <summary style={{ fontSize: 7, color: '#333', cursor: 'pointer' }}>{t('script.analysis')}</summary>
                    <pre style={{ fontSize: 7, color: '#3B1D8F', whiteSpace: 'pre-wrap', wordBreak: 'break-all', margin: '4px 0 0 8px' }}>
                      {shot.prompts['node_10']}
                    </pre>
                  </details>
                )}
              </div>
            );
          })}
        </div>
      </details>
    </div>
  );
}
